{% set name = "premise" %}
{% set version = environ.get('VERSION', "0.0.0") %}


package:
  name: {{ name }}-{{ bw }}
  version: {{ version }}

source:
  path: ..


{% set bw2data_versions = {
    "bw2": "bw2data <4.0.0",
    "bw25": "bw2data >=4.0.0"
} %}

build:
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

test:
  imports:
    - premise


requirements:
  host:
    - python
    - setuptools
  run:
    - {{ bw2data_versions[bw] }}
    - python
    - bottleneck
    - bw2io
    - ecoinvent_interface
    - constructive_geometries>=0.9.5
    - cryptography
    - datapackage
    - numpy <2.0.0
    - pandas
    - platformdirs
    - prettytable
    - pyarrow
    - pycountry
    - pyYaml
    - requests
    - schema
    - scipy<1.14.0
    - sparse>=0.14.0
    - wurst>=0.4
    - xarray<=2024.2.0
    - tqdm
    - unfold

channels:
  - conda-forge
  - defaults


about:
  home: https://github.com/polca/premise
  license: BSD License
  summary: 'Coupling Integrated Assessment Models and Life Cycle Assessment.'
license_family: BSD
license_file: LICENSE