name: Accessibility Scanner
on: workflow_dispatch

jobs:
  accessibility_scanner:
    runs-on: ubuntu-latest
    steps:
      - uses: github/accessibility-scanner@v2
        with:
          urls: | 
            https://github.com/polca/premise
          repository: polca/premise
          token: ${{ secrets.GH_TOKEN }}
          cache_key: cached_results-premise.json